import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from "react-icons/ai";
import { BsFillMoonStarsFill, BsFillPatchCheckFill } from "react-icons/bs";
import SwiperCore, { Navigation } from "swiper";
import "swiper/swiper-bundle.css";
import deved from "../public/ozi.png";
import ME from "../public/gunung.jpg";
import Image from "next/image";
import AOS from "aos";
import "aos/dist/aos.css";
import exp from "../public/work.jpg";

SwiperCore.use([Navigation]);

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  const portfolioData = [
    {
      image: "/catatan.png",
      title: "MyCatatan",
      desc: "Aplikasi pencatatan sederhana berbasis React yang memungkinkan pengguna membuat, mengarsipkan, dan mencari catatan. Data disimpan secara lokal melalui localStorage.",
      view: "https://catatan-react-chi.vercel.app/",
      demo: "",
      techStack: ["React Js", "LocalStorage", "CSS"]
    },
    {
      image: "/porto3.png",
      title: "Culinarix",
      desc: "Culinarix  merupakan aplikasi rekomendasi kuliner di kota bandung untuk membantu wisatawan ataupun masyarat lokal disana menemukan rekomendasi kuliner yang sesuai dengan preferensi mereka.",
      view: "https://github.com/keeptrain/Culinarix?tab=readme-ov-file",
      demo: "https://www.youtube.com/watch?feature=shared&v=_1JeLwmAOOE",
      techStack: ["Flask", "Docker", "Firestore", "GCP "]
    },
    {
      image: "/uikit.png",
      title: "UIKIT Website",
      desc: "Website ini merupakan Website Jual Beli UI KIT Figma dengan sistem subscription dengan midtrans.Website ini dibangun menggunakan VueJs 3 dan backend nya menggunakan laravel .                              ",
      view: "https://github.com/alghoziii/FE-UI-KIT",
      techStack: ["VueJs", "MySQL", "Tailwind", "Laravel"]
    },
    {
      image: "/porto1.png",
      title: "KASIRQ",
      desc: "Mengembangkan sistem kasir berbasis Website (Software as a Service) untuk memudahkan manajemen penjualan toko obat tanaman dan pupuk. Website ini dilengkapi sistem subscription sesuai paket yang dipilih .",
      view: "https://dashboard-kasir.vercel.app/",
      demo: "https://dashboard-kasir.vercel.app/",
      techStack: ["PHP Native", "MYSQL", "Tailwind"]

    },

    {
      image: "/travela.png",
      title: "Travela",
      desc: "Travela Merupakan website booking paket travel secara online yang dibangun menggunakan PHP Laravel 11. Website ini dilengkapi fitur autentikasi pengguna, role-based access control (menggunakan Spatie), content management system untuk admin, checkout dan approval sistem, serta katalog paket tour. ",
      view: "https://github.com/alghoziii/Travela",
      techStack: ["Laravel", " Mysql", "Tailwind",]

    },
    {
      image: "/booking.png",
      title: "Mini Soccer Booking",
      desc: "Website pemesanan lapangan mini soccer online yang dibangun dengan arsitektur microservices menggunakan Gin & Golang, dilengkapi fitur autentikasi pengguna, cek ketersediaan jadwal lapangan secara real-time,order lapangan dan pembayaran online(Midtrans)",
      view: "https://github.com/alghoziii/mini-soccer-booking",
      techStack: ["Golang", " PostgreSql", "Docker", "GCP", "NEXTJS"]

    },
  ];

  const experiences = [
    {
      period: "Agt 2024 - Jan 2025",
      title: "FULL STACK DEVELOPER",
      company: "Horus Technology(internship)",
      location: "Gamping,Yogyakarta",
      url: "https://www.horus.co.id/",
    },
    {
      period: "Agt 2024 - Jan 2024",
      title: "Cloud Computing",
      company: "Bangkit (Studi Independent)",
      location: "Bandung, Indonesia (Remote)",
      url: "https://grow.google/intl/id_id/bangkit/",
    },
  ];

  useEffect(() => {
    AOS.init({
      duration: 1100,
      once: true,
      mirror: false,
    });

    AOS.refresh();

    return () => {
      AOS.refresh();
    };
  }, []);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-4 dark:bg-gray-900 md:px-8 lg:px-16">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portofolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="https://drive.google.com/file/d/1T4Y2qRci9l4_oDT8FgZ12C4dlzpoRgwE/view?usp=sharing">
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden md:h-90 md:w-99 bottom-11" data-aos="fade-down">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
          <div className="text-center p-5 py-1" data-aos="fade-up" data-aos-anchor-placement="center-bottom">
            <h2 className="text-2xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-4xl ">Shobarudin Alghozi</h2>
            <h3 className="text-ls py-3 dark:text-white md:text-3md">Backend Web Developer</h3>
          </div>
          <div className="flex justify-center gap-10 py-3 text-gray-600 dark:text-gray-400" data-aos="fade-up">
            <a href="https://github.com/alghoziii" target="_blank" rel="noopener noreferrer" className="text-4xl hover:text-gray-800 transition-colors duration-300">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/shobarudin-alghozi-550163217/" target="_blank" rel="noopener noreferrer" className="text-4xl hover:text-blue-500 transition-colors duration-300">
              <AiFillLinkedin />
            </a>
            <a href="https://instagram.com/alghozii_zy" target="_blank" rel="noopener noreferrer" className="text-4xl hover:text-pink-500 transition-colors duration-300">
              <AiFillInstagram />
            </a>
          </div>

        </section>

        <section id="about" className="py-12">
          <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 text-center mb-8" data-aos="fade-down">
            About Me
          </h3>

          <div className="flex flex-col md:flex-row items-center bg-gray-100 dark:bg-gray-900 rounded-xl shadow-lg p-6 mx-auto max-w-5xl" data-aos="fade-up">
            {/* Image Container - Closer to text */}
            <div className="w-full md:w-2/5 mb-6 md:mb-0 md:mr-8">
              <div className="relative aspect-square w-full rounded-xl overflow-hidden shadow-md">
                <Image
                  src={ME}
                  alt="Profile Photo"
                  layout="fill"
                  objectFit="cover"
                  className="hover:scale-105 transition-transform duration-300 rounded-lg"
                />
              </div>
            </div>

            {/* Content Container - Better aligned */}
            <div className="w-full md:w-3/5 max-w-xl flex flex-col">
              <div className="flex-grow">
                <p className="text-gray-700 dark:text-gray-300 mb-8 leading-relaxed text-lg max-w-prose px-6 text-justify ">
                  I'm a passionate web developer specializing in backend development.
                  I have a deep enthusiasm for technology and continuously seek opportunities to expand my knowledge and skills.
                  I thrive in collaborative environments, delivering efficient solutions, and contributing to innovative projects that drive positive change.
                  I am open to diverse job opportunities that align with my expertise and interests.
                </p>
              </div>



              {/* Button aligned to right */}
              {/* <div className="flex justify-end mt-4">
                <a
                  href="https://www.linkedin.com/in/shobarudin-alghozi-550163217/"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-block bg-teal-500 hover:bg-teal-600 text-white font-medium py-2 px-6 rounded-lg transition-colors duration-300"
                >
                  Know Me More
                </a>
              </div> */}
            </div>
          </div>
        </section>


        <section id="experience" className="py-12">
          <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 text-center mb-8" data-aos="fade-down">
            My Experience
          </h3>

          <div className="flex flex-col md:flex-row items-stretch justify-center bg-gray-100 rounded-lg shadow-md dark:bg-gray-900 p-6 mx-auto max-w-6xl" data-aos="fade-down">
            {/* Image Container - Full Height */}
            <div className="mt-12">
              <div className="relative h-full w-full rounded-lg overflow-hidden">
                <Image
                  src={exp}
                  alt="Work Experience"
                />
              </div>
            </div>

            {/* Experiences List - Better Card Sizing */}
            <div className="w-full md:w-2/3 space-y-6">
              {experiences.map((exp, index) => (
                <a
                  key={index}
                  href={exp.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="block p-5 bg-white dark:bg-gray-800 rounded-lg shadow hover:shadow-md transition-all duration-300 ml-auto hover:-translate-y-1 hover:border-l-4 hover:border-teal-500"
                  style={{ maxWidth: "90%" }}
                >
                  <div className="text-gray-700 dark:text-green-400 font-medium">{exp.period}</div>
                  <h4 className="text-xl font-bold text-gray-800 dark:text-white mb-1">{exp.title}</h4>
                  <div className="text-gray-700 dark:text-gray-300 font-medium">{exp.company}</div>
                  <div className="text-gray-600 dark:text-gray-400 text-sm">{exp.location}</div>
                  <div className="mt-2 text-teal-500 text-sm flex items-center">
                    View details <span className="ml-1">→</span>
                  </div>
                </a>
              ))}
            </div>
          </div>
        </section>

        <section id="experience">
          <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 mt-16 text-center mb-11" data-aos="zoom-in">
            My Skills
          </h3>
          <div className="container experience__container dark:text-white" data-aos="zoom-in">
            <div className="experience__fontend">
              <h3>Frontend Development</h3>
              <div className="experience__content mt-6">

                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Javascript</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>PHP</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Vue Js</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Laravel</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>React Js</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
              </div>
            </div>
            <div className="experience__backend">
              <h3>Backend Development | Cloud Computing</h3>
              <div className="experience__content mt-6">
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Python</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Node JS</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Flask</h4>
                    <small className="text-light">Intermediate</small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Golang</h4>
                    <small className="text-light">Pre-intermediate </small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Google Cloud Computing</h4>
                    <small className="text-light">Intermediate </small>
                  </div>
                </article>
                <article className="experience__details">
                  <BsFillPatchCheckFill className="experience__details-icon" />
                  <div>
                    <h4>Mysql & PostgreSql</h4>
                    <small className="text-light">Intermediate </small>
                  </div>
                </article>
              </div>
            </div>
          </div>
        </section>

        <section className="py-12 bg-gray-100 dark:bg-gray-900">
          <div className="container mx-auto px-4">
            <h3 className="text-3xl py-1 text-teal-600 dark:text-teal-400 text-center mb-12">Portfolio</h3>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {portfolioData.map((item, index) => (
                <div
                  key={index}
                  className="bg-white dark:bg-gray-800 rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition-shadow duration-300"
                  data-aos="fade-up"
                >
                  <div className="relative h-60 w-full overflow-hidden">
                    <img
                      src={item.image}
                      alt={item.title}
                      className="w-full h-full object-cover transition-transform duration-500 hover:scale-110"
                    />
                  </div>
                  <div className="p-6">
                    <h4 className="text-xl font-bold text-gray-800 dark:text-white mb-3">{item.title}</h4>
                    <p className="text-gray-600 dark:text-gray-300 mb-6 text-justify">{item.desc}</p>

                    {/* Unique Tech Stack for Each Project */}
                    <div className="flex flex-wrap gap-4 mb-6">
                      {item.techStack?.map((tech, i) => (
                        <span
                          key={i}
                          className="bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-200 px-3 py-1 rounded-full text-sm"
                        >
                          {tech}
                        </span>
                      ))}
                    </div>

                    <a
                      href={item.view || item.demo || '#'}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block w-full bg-teal-500 hover:bg-teal-600 text-white text-center py-2 px-4 rounded-lg transition-colors duration-300"
                    >
                      Lihat Detail
                    </a>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
